export enum ESvgIcons {
	HELP = 'help',
	NOTIFICATION = 'notification',
	LOGIN = 'login',
	EDIT_SSP = 'edit-ssp',
	PAUSE_SSP = 'pause-ssp',
	DELETE_SSP = 'delete-ssp',
	SEARCH = 'search',
	CLOSE = 'close',
	SETTINGS = 'settings',
	FILTER = 'filter_list',
	INSTANT_MIX = 'instant_mix',
	STATISTIC = 'statistic',
	INFO = 'info',
	PERCENT = 'percent',
}
